API_KEY = '5cURxrEcO1PMvD7yx2UDsWivvecMqgjovDP56RWeGasoaVPB9OSEbvKzdnvfKEcO'
SECRET_KEY = '5GbzEESXrAKvAil8WSdYdgmaDDYaj8mxElNNF4GSMqtWvx5ZLmzEo2U0jfhKejec'


RSIOVERBOUGHT=70
RSIOVERSOLD = 30
RSIPERIOD = 18
QUANTITY= 25
in_position = True